name: Lint Java code

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Checkstyle
        run: |
          sudo apt update
          sudo apt install checkstyle

      - name: Lint Java code
        run: checkstyle -c checkstyle.xml src
